services:
  db:
    image: postgres:17
    shm_size: '1gb'
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: contextual
      POSTGRES_PASSWORD: contextual

